### ISSUE TITLE
TabNine auto completions not working

### ISSUE THREAD

**Issue by IPWright83** [codota/tabnine-sublime#69]
**please complete the following information:**	
 - OS version: Ubuntu
 - Editor version: Sublime 3
 - Programming language: JavaScript
 - TabNine extension version: 3.0.4 (Sublime Plugin)
 
I've been talking with @dimacodota already, but essentially tab is only auto-completing the first result before then falling back (I think) to sublime autocomplete.

There's also this in the logs:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 478, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 619, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "/home/iw651/.config/sublime-text-3/Packages/TabNine/completions/completions_v2.py", line 91, in on_activated
    view.window().status_message("TabNine")
AttributeError: 'NoneType' object has no attribute 'status_message'
git: tracking working dir /home/iw651/src/mobileApp/myuoy
no such context scope:source.groovy#prototype at line 9 column 16 in Packages/zzz A File Icon zzz/aliases/Groovy (Gradle).sublime-syntax
Exception while interacting with TabNine subprocess: No JSON object could be decoded
TabNine: starting version 3.1.5
```

**Comment by AntoineAugusti** [comment]
I get this stracktrace

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 627, in on_activated_async
    callback.on_activated_async(v)
  File "/Users/antoineaugusti/Library/Application Support/Sublime Text 3/Packages/TabNine/completions/completions_v1.py", line 146, in on_activated_async
    tabnine_proc.request(request)
  File "/Users/antoineaugusti/Library/Application Support/Sublime Text 3/Packages/TabNine/tab_nine_process.py", line 115, in request
    req = json.dumps(req)
AttributeError: 'NoneType' object has no attribute 'dumps'
```

**Comment by IPWright83** [comment]
@dimacodota should I still be seeing none TabNine suggestions in this list?

![image](https://user-images.githubusercontent.com/1374775/95759917-4530e680-0ca2-11eb-87a2-7d86bfad43fd.png)

**Comment by dimacodota** [comment]
@IPWright83  If you mean the 'Instanceof' keyword? then yes, it was intentional, not to remove existing completion contributors

**Comment by IPWright83** [comment]
@dimacodota yeah, I was surprised that the `let` and `keyword` options were in there. I guess this is how you enable the snippet functionality by leaving those present?

**Comment by dimacodota** [comment]
yes, exactly
